import type { Metadata } from 'next';
// import './globals.css';
// 佈景樣式context provider
import { ThemeProvider } from '@/context/theme';
// 佈景切換元件
import ThemeSwitch from './_components/theme-switch';
// 購物車context provider
import { CartProvider } from '@/context/cart';
// 會員context provider
import { UserProvider } from '@/context/user';
import { Inter, Noto_Sans } from 'next/font/google';
import { cn } from '@/lib/utils';

const notoSansHeading = Noto_Sans({
  subsets: ['latin'],
  variable: '--font-heading',
});

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'React課堂範例',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn('font-sans', inter.variable, notoSansHeading.variable)}
    >
      <body className="min-h-full flex flex-col">
        {/* 第3-2步: 最外層元件包裹Provider元件，提供Context給其下的後代元件 */}
        <ThemeProvider>
          {/* 先註解掉，要測試theme可以開啟 */}
          {/* <ThemeSwitch /> */}
          <UserProvider>
            <CartProvider>{children}</CartProvider>
          </UserProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
